---
title: "Initial Ideas"
author: "Luca Carbone"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
        number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>

# Topics

| <font size="4"> • Ideas from: [R Basic ECPR 2018](https://github.com/aakosm/R_Basics_ECPR) </font>

<br>

# Overview course
* **<span style="color:black">First week ()</span>**
  + **Setting up** [R](https://www.freestatistics.org/cran/) and [RStudio](https://rstudio.com/products/rstudio/download/);
  + **Basic objects** - vector, matrix, data frame, list, data types;
  + **Simple calculations**;
  + **Descriptives** - importing/exporting data, summarising;
  + **Handling objects** - indexing.

* **<span style="color:black">Second week ()</span>**
  + **Wrangling** - tidyverse;
  + **Functions** - loops, conditionals (if else, ifelse, while), function, apply family.

* **<span style="color:black">Third week ()</span>**
  + **Loading/saving data** - SPSS data (heaven/foreign package);
  + **GLM** - .

* **<span style="color:black">Fourth week ()</span>**
  + **SEM** - lavaan and structural plotting;
  + **Missing data** - multiple imputations.

* **<span style="color:black">Fifth week ()</span>**
  + **Basic plotting**;
  + **Fancy plotting** - ggplot.

* **<span style="color:black">Sixth week ()</span>**
  + **RMarkdown** - handling citations, write a paper in R, open science;
  + **Additional questions**


## First week (Lu)

| • install R and RStudio

<br>

### first session

| • what, why, and intro to course
| • a word of encouragement and how to find help
| • good coding
| • practical matters: Rstudio environment, installing/loading packages
| • simple calculations: storing, operators

<br>

### second session

| • basic objects: vector, matrix, data frame, list, data types (numeric, character, logical, factors, missing values)
| • descriptives: importing/exporting data, summarising
| • operations with objects and indexing

<br>

## Second week (Lu)

| • wrangling: tidyverse, 
| • loops, conditionals (if else, ifelse, while), function, apply family

<br>

## Third week (Le)

| • loading/saving data (heaven/foreign package)
| • GLM

<br>

## Fourth week (Se)

| • SEM and structural plotting
| • Missing data

<br>

## Fifth week (Lu)

| • basic plotting
| • ggplot
| • plotly

<br>

## Sixth week (Se)

| • RMarkdown: citation, write a paper in R, embed analyses, open science (power analysis, reproducible simulations with use.seed())
| • additional questions

<br>

# Format (duration, audience, frontal/exercises)

<br>

## Session

| • 20/30 mins theory and 20/30 mins practice x2

<br>

## Data

| <font size="4"> • [Iris](https://gist.github.com/curran/a08a1080b88344b0c8a7) </font>
| • individual contribution

<br>

# Guides

| <font size="4"> • [RMarkdown by Yihui Xie, J. J. Allaire & Garrett Grolemund](https://bookdown.org/yihui/rmarkdown/) </font>
| <font size="4"> • [R course by Danielle Navarro](https://learningstatisticswithr.com) </font>
| <font size="4"> • [R resources by Paul Vanderlaken](https://paulvanderlaken.com/2017/08/10/r-resources-cheatsheets-tutorials-books/) </font>

<br>

# TO DO

| • online survey to ask what topics to include
| • other topics to add: factor analysis, good practices for reproducibility (use set.seed(),)





